default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  port: 3306
  database: <%= Settings.db.default.database %>
  host:     <%= Settings.db.default.host %>
  username: <%= Settings.db.default.username %>
  password: <%= Settings.db.default.password %>


development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
